name: LANDO
channels:
  - conda-forge
dependencies:
  - cmake
  - gdal
  - proj
  - octave
  - gnuplot
  - octave_kernel
  - texinfo
  - cxx-compiler
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - nbclient
  - nbconvert
  - nbformat
  - notebook
  - psycopg2
  - scipy
  - sqlalchemy
  - dask
  - distributed
  - ipyfilechooser
  - ipysheet
  - openpyxl
  - jupyterlab-sos
  - pip
  - pyarrow
  - r-arrow
  - r-terra
  - r-changepoint
  - r-doparallel
  - r-dorng
  - r-dosnow
  - r-dplyr
  - r-ff
  - r-foreach
  - r-forecast
  - r-intcal
  - r-nloptr
  - r-r.devices
  - r-plyr
  - r-rcpp
  - r-remotes
  - r-sets
  - r-tidyverse
  - r-raster
  - r-rstan
  - r-usethis
  - pip:
      - sos==0.24.0
      - sos-python==0.20.0
      - sos-notebook==0.24.0
      - sos-r==0.20.0
      - sos-matlab==0.20.0
      - joblib==0.17.0
      - xlrd==1.2.0
      - ipykernel==6.15.0
      - ipywidgets==8.0.2
      - ipython==8.4.0
      - jupyter_contrib_core
  