name: LANDO
channels:
  - conda-forge
dependencies:
  - matplotlib==3.3.3
  - numpy==1.19.4
  - pandas==1.1.5
  - seaborn==0.11.0
  - sos-python==0.18.4
  - sos-r==0.19.6
  - octave_kernel==0.32.0
  - jupyter_client==6.1.7
  - jupyter_core==4.7.0
  - jupyter_server==1.11.2
  - nbclient==0.5.1
  - nbconvert==6.0.7
  - nbformat==5.0.8
  - notebook==6.1.5
  - psycopg2==2.8.6
  - scipy==1.5.3
  - sqlalchemy==1.3.20
  - dask==2021.10.0
  - distributed==2021.10.0
  - pyarrow
  - ipyfilechooser
  - pip
  - jupyterlab-sos
  - pip:
      - IPython==7.26.0
      - sos==0.22.5
      - sos-notebook==0.22.6
      - sos-matlab==0.18.5
      - joblib==0.17.0
      - xlrd==1.2.0
      - ipykernel==6.0.3