library("devtools")
options(unzip = "internal")
install_github("earthsystemdiagnostics/hamstr", ref="master")
install.packages("Bchron", repos = "https://cloud.r-project.org")
install_github("edwindj/ffbase", subdir="pkg")
install_github("earthsystemdiagnostics/hamstrbacon", ref="main")
install_github("Maarten14C/rbacon", ref="master")
install_version("clam", version="2.3.9", repos= "https://cloud.r-project.org")